# autogenerated by meta.py
from typing import Literal, overload
class Event:
    kind: str
    params: dict[str, object]

    @overload
    def __init__(self, kind: Literal["input_name"]) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["select_class"], *, classes: list[str]) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["take_damage"], *, name: str, dmg: float) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["output_stats"], *, name: str, hp: float, mana: float) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["upgrade_actions"], *, actions: list[str]) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["invalid_input"]) -> None: ...
    