
# autogenerated by meta.py
from typing import Literal, overload
class Event:
    kind: str
    params: dict[str, object]

    @overload
    def __init__(self, kind: Literal["take_damage"], /, name: str, dmg: float) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["output_stats"], /, name: str, hp: float, mana: float) -> None: ...
    