# autogenerated by meta.py
from typing import Literal, overload
class Event:
    kind: str
    params: dict[str, object]

    @overload
    def __init__(self, kind: Literal["input_name"]) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["select_class"], *, classes: list[str]) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["select_starting_actions"], *, actions: list[str]) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["start_turn"], *, name: str) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["select_action"], *, actions: list[str]) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["select_target"], *, enemies: list[str]) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["take_damage"], *, name: str, dmg: float) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["output_stats"], *, name: str, hp: float, mana: float) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["level_up"], *, name: str, level: int) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["level_up_actions"], *, actions: list[str]) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["gain_new_actions"], *, actions: list[str]) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["upgrade_action"], *, action_name: str, upgrades: list[str]) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["long_rest"], *, name: str) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["short_rest"], *, name: str) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["invalid_input"]) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["win_encounter"]) -> None: ...
    
    @overload
    def __init__(self, kind: Literal["lose"]) -> None: ...
    