# autogenerates an events.pyi for nice typechecking purposes
import os.path
import json

text = json.load(open(os.path.abspath("src/instances/text.JSON")))
events: str = """# autogenerated by meta.py
from typing import Literal, overload
class Event:
    kind: str
    params: dict[str, object]
"""

def add_override(kind: str, params: dict[str, str]) -> None:
    global events

    """adds override

    Args:
        kind (str): the kind parameter for the override
        params (dict[str, str]): param name: param type
    """
    str_params: str = ""
    for param in params.keys():
        str_params += f", {param}: {params[param]}"
    overload: str = f"""
    @overload
    def __init__(self, kind: Literal["{kind}"], /{str_params}) -> None: ...
    """
    events += overload

types: dict[str, str] = text["param_types"]


prompts: dict[str, list[str]] = text["events"]

for name, messages in prompts.items():
    params: dict[str, str] = {}
    for message in messages:
        for placeholder, type_ in types.items():
            if "{" + placeholder + "}" in message:
                params[placeholder] = type_
    add_override(name, params)

with open("src/engine/events.pyi", "w", encoding="utf-8") as f:
    f.write(events)